name = "r2-metadata-worker"
main = "src/index.ts"
compatibility_date = "2025-04-28"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "nodo-media-dev"

[triggers]
crons = ["0 0 * * *"]

account_id = "49ef1ba682ad8cfd720c86699ae17521"